# Generated by Django 5.2.1 on 2025-06-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_method',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
