# Generated by Django 5.2.1 on 2025-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_pedido_order_pagamento_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_completo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='pagamento_method',
            field=models.CharField(choices=[('Dinehriro na Entrega', 'Dinehriro na Entrega'), ('Knalti', 'Knalti')], default='Dinehriro na Entrega', max_length=20),
        ),
    ]
